### ISSUE TITLE
Proposal for a "geo-arrow" format

### ISSUE THREAD

**Issue by TomAugspurger** [opengeospatial/geoparquet#1]
Various members of the Python and R geospatial communities are working on a [geo-arrow-spec](https://github.com/geopandas/geo-arrow-spec): a way to store geospatial data in Apache Arrow (and Apache Parquet) format. This issue is to introduce the cdw-geo and geo-arrow-spec groups, and hash out a plan for how to proceed, since there's some overlap between the two groups' goals.

In addition to intros, I wanted to address *Why another parquet format*?

The [geoparquet](https://github.com/opengeospatial/cdw-geo/blob/main/format-specs/geoparquet.md) format will likely store  geometries using something like WKB. The geo-arrow-spec hasn't settled on a representation for geometries (see https://github.com/geopandas/geo-arrow-spec/issues/4 and https://github.com/geopandas/geo-arrow-spec/issues/3), but it will likely move away from using WKB to an "arrow native" memory layout. https://github.com/geopandas/geo-arrow-spec/issues/4#issuecomment-632270143 has more information on why, but the short version is that the arrow-native layout a.)  doesn't require decoding WKB to use the geometries, b.) coordinates are contiguous in memory, c.) provides random access to geometries without having to parse unnecessary data.

---

Some logistical questions (with my recommendations):

1. Would a version of the geo-arrow-spec be appropriate for inclusion in cdw-geo? (I think so, as long as we think having two parquet formats won't confuse people)
2. geo-arrow-spec still needs to work out some details, including the memory layout of geometries. Where should development on geo-arrow-spec happen? (I think keep in in geo-arrow-spec, since not everyone in cdw-geo will care. Once it's more stable, we can consider moving it out of geopandas/geo-arrow-spec and into this repository, if both groups agree).

cc @jorisvandenbossche from the geo-arrow-spec side.

**Comment by cholmes** [comment]
Sorry for the slow response on this, thanks for creating the issue. Great to meet you @jorisvandenbossche - it's awesome work you're doing.

I definitely think geo-arrow-spec makes sense for inclusion in cdw-geo. Though I think eventually this repository may drop away in favor of actual specs. It does seem like it'd make sense to eventually have one 'geoparquet' place, where it explains both formats, if that's what ultimately ends up making sense.

And I agree on keeping development of geo-arrow-spec in the geopandas repository. 

I'm definitely interested to see the evolution of the geo-arrow-spec and the arrow-native layout. This effort I think does make sense to start with WKB, since most vendors already use it, but I can imagine some might be interested in a more efficient format if they start to try to read data in place.

**Comment by jorisvandenbossche** [comment]
Looking at https://github.com/opengeospatial/cdw-geo/pull/2, I have a general question: currently it defines a metadata standard that is quite close to what we did in GeoPandas / geo-arrow-spec, but not _exactly_. So the existing geo-parquet files written by geopandas (and R's sfarrow) are not actually compatible with this. 
(I know the geo-arrow-spec is also about in-memory Arrow data, but in practice it's currently mostly used for Parquet files). 

I think ideally we only want a single metadata specification for Parquet on the long term? So that means we need to discuss the differences / see how the two can be aligned?

**Comment by TomAugspurger** [comment]
I'm happy to move the column metadata to the file level. I didn't realize geo-arrow-spec put it at the file level until after my first write up (@jorisvandenbossche do you have a sense for whether using both file and column-level metadata is common in parquet?). 

I picked "geoparquet" as the top-level key to avoid clashing with geo-arrow-spec for now, but I agree that long-term we want just one standard. If we can get everyone on the same page, then just using "geo" as the key seems reasonable.

Maybe we talk through CRS / epsg stuff in https://github.com/opengeospatial/cdw-geo/issues/3?

Adding in those additional fields like `bbox` seems reasonable. I kept the very first draft here small to just get things rolling.

**Comment by jorisvandenbossche** [comment]
> I kept the very first draft here small to just get things rolling.

And BTW, thanks for getting things rolling again!

**Comment by echeipesh** [comment]
Came across similar idea implemented in GeoMesa Parquet Filesystem DataStore. ode links: [Parquet Writer Test](https://github.com/locationtech/geomesa/blob/main/geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/test/scala/org/locationtech/geomesa/parquet/ParquetReadWriteTest.scala) and [WriteSupport](https://github.com/locationtech/geomesa/blob/main/geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/io/SimpleFeatureWriteSupport.scala)

Writing MultiPolygon produces following schema:

```
❯ pqrs schema geomesa.parquet
Metadata for file: geomesa.parquet

version: 1
num of rows: 45962
created by: parquet-mr version 1.9.0 (build 38262e2c80015d0935dad20f8e18f2d6f9fbd03c)
metadata:
  geomesa.fs.sft.name: level2
  geomesa.parquet.version: 1
  writer.model.name: SimpleFeatureWriteSupport
  geomesa.fs.sft.spec: *geom:MultiPolygon:org.geotools.jdbc.nativeTypeName=MULTIPOLYGON:org.geotools.jdbc.nativeType=12:hasGeopkgSpatialIndex=true:nativeSRID=4326:COORDINATE_DIMENSION=2,GID_0:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,NAME_0:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,GID_1:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,NAME_1:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,NL_NAME_1:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,GID_2:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,NAME_2:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,VARNAME_2:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,NL_NAME_2:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,TYPE_2:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,ENGTYPE_2:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,CC_2:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT,HASC_2:String:org.geotools.jdbc.nativeType=12:org.geotools.jdbc.nativeTypeName=TEXT
message level2 {
  OPTIONAL group geom {
    REQUIRED group x (LIST) {
      REPEATED group list {
        REQUIRED group element (LIST) {
          REPEATED group list {
            REPEATED DOUBLE element;
          }
        }
      }
    }
    REQUIRED group y (LIST) {
      REPEATED group list {
        REQUIRED group element (LIST) {
          REPEATED group list {
            REPEATED DOUBLE element;
          }
        }
      }
    }
  }
}
```

This looks like a pretty big win. In particular because this splits x/y into two columns this allows using parquet min/max stats to be used for spatial filtering.

One thing I'm not clear on is if it's possible to have the same parquet schema be used for all geometry types or if the one would be forced back to WKB encoding as soon as you have Points and Lines sharing the same column.

**Comment by elahrvivaz** [comment]
Yes, GeoMesa uses something similar to the "arrow native" format being described above. You can see the arrow field definitions [here](https://github.com/locationtech/geomesa/blob/geomesa-3.3.0/geomesa-arrow/geomesa-arrow-jts/src/main/java/org/locationtech/geomesa/arrow/vector/GeometryFields.java#L102-L152), and the parquet ones [here](https://github.com/locationtech/geomesa/blob/geomesa-3.3.0/geomesa-fs/geomesa-fs-storage/geomesa-fs-storage-parquet/src/main/scala/org/locationtech/geomesa/parquet/io/SimpleFeatureParquetSchema.scala#L176-L214).

From working with it, the pros and cons to this approach are as follows, in no particular order:

Pros:
* Don't need WKB parsing code to read the files
* Can take advantage of native column encoding/compression/chunk skipping
* Can push down predicates into native (parquet) filters

Cons:
* Have to fall back to WKB when dealing with different geometry types in a single column
* Doesn't interop well with Spark's parquet writing, which doesn't handle nested/repeated fields (last I checked)
* Doesn't account for Z/M values (although could be extended to do so)

**Comment by thomcom** [comment]
I'm excited to see this spec developing!

**Comment by kylebarron** [comment]
Now that https://github.com/opengeospatial/geoparquet/pull/191 has been merged, I'm going to close this. Also refer to the geoarrow spec at https://github.com/geoarrow/geoarrow
