### ISSUE TITLE
What are the Allowed Geometry Types?

### ISSUE THREAD

**Issue by achapkowski** [opengeospatial/geoparquet#119]
The documentation just states that the geometry_type can be list or a single string. Does this mean we can pass the geometry_type as [Point, MultiPoint] or does it have to be a string: "Point,MultiPoint" for multiple geometries? 

Also in the md file the allowed geometry enums are not listed.

**Comment by jorisvandenbossche** [comment]
> The documentation just states that the geometry_type can be list or a single string. Does this mean we can pass the geometry_type as [Point, MultiPoint] or does it have to be a string: "Point,MultiPoint" for multiple geometries?

Each string needs to correspond to one of the allowed values, and thus a list can be used to specify multiple types like `["Point", "MultiPoint"]`


> Also in the md file the allowed geometry enums are not listed.

https://github.com/opengeospatial/geoparquet/blob/753f727eaa8ae74a1bf0f0a5aa674bd9437cb9b4/format-specs/geoparquet.md?plain=1#L113-L118

**Comment by jatorre** [comment]
So, are we good on this one?

**Comment by cholmes** [comment]
Closing this, since it seems like we provide enough guidance in the spec itself, but feel free to re-open if there's more we should say. 

This could be a good 'sample data' that we provide, a couple geoparquet files that use multiple geometry types, that implementations can use to test against, and also provide complete examples for people.
